sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    packages:
    - libqt5webkit5-dev
    - qtdeclarative5-dev


script:
  - echo hello
#  - javac Hello.java
#  - java Hello
